src/server.js
As per this issue https://github.com/shortlist-digital/tapestry-wp/issues/22
However this is still spitting out the entirety of the applications CSS, I read and re-read the Glamor docs but couldn't get it to work. The `rehydrate` method shouldn't have any impact on this, as far as I'm aware, but implementing exactly as per the docs still gives me more CSS than I want.
=> Switched the glamor method to renderStaticOptimized

bin/tapestry, bin/tapestry-build, bin/tapestry-dev, bin/tapestry-start
This is an update of the CLI for __tapestry-wp__ only, it still boots up the same build/start scripts as before. This follows the example set by __next__ – creating separate scripts to handle the different tasks. These will eventually be fleshed out like __next__, for now they just use the existing set up.
I've added `'use strict'` in some files that use `const`/`let` as I just ran this in Node v4.7 and got errors that those things can only be used in `strict mode`.
=> Update CLI, create separate scripts to handle different tasks

bin/tapestry-build, bin/tapestry-dev, bin/tapestry-start, src/default-html.js, src/server.js, src/webpack.config.js
Added `chunkhash` to output bundle name, shuffled around some of the output directories, transpiled component tree now lives under `.tapestry/app/` so our new `assets.json` can live in the `.tapestry` directory.
This allows us to provide longterm caching of our output JS bundle.
Tested on our local Tapestry dev example project.
=> Hash bundle

bin/tapestry-dev, src/build.js, src/server.js
Server/Client now kept up-to-date with latest project changes. In dev mode the require cache is cleared to allow re-requiring the latest project files, `webpack` has been configured to run a `watch` and re-compile the client on change.
Project development experience was _poor_
=> Improve user dev experience

.lintstagedrc, package.json, src/build.js
Added `pre-commit`, `lint-staged` and `editorconfig-tools` to allow pre-commit linting/testing
It was real crummy committing/pushing/deploying code that broke tests, this will prevent any commits that fail tests or linting specs.
=> Add pre commit scripts

src/webpack/client.config.js
Enabled source maps when running dev mode
To improve the developer experience
No breaking tests, working locally
=> Enable sourcemaps

package.json, src/client/index.js, src/client/webpack.entry.js, src/server/render/default-html.js, src/shared/default-routes.js, src/utilities/validator.js, src/webpack/shared.js, test/tests/routing.test.js
Static routes can now be asynchronously loaded via code-splitting.
```js
export default {
routes: [{
path: 'async-path-yo',
getComponent: (loc, cb) =>
import('./path/to/component.js')
.then(module => cb(null, module.default))
.catch(err => console.error(err))
}],
siteUrl: 'http://url'
}
```
The less JS we load the better!
Added a test
=> Allow async static routes

package.json, src/server/handle-api.js, src/server/handle-dynamic.js, src/server/index.js, src/utilities/cache-manager.js, test/tests/document.test.js
I've added an in [memory cache](https://github.com/isaacs/node-lru-cache). It will cache the last 100 responses to the API and the renderHTML method, for 2 minutes each
This drastically improves response times for the top 100 hit pages of a Tapestry site
The end-to-end integration tests still work, and there's not much code here so I feel like restructuring, code into unit testable methods (assert "loadFromCache" was called etc) would be testing node-lru-cache rather than tapestry.
=> In memory caching of HTML render and API requests

src/client/webpack.entry.js, src/shared/loader-categories.js, src/shared/loader-front-page.js, src/shared/loader-page.js, src/shared/loader-post.js
Removed loader references to window.scrollTo, I've seen weird visual bugs, and I feel like it's being called multiple times as pages switch around. 
It should be defined in use land in the supplied `onPageUpdate` method.
This wasn't actually being called - so I've fixed that too.
This contains the code that is experiencing issue: https://github.com/shortlist-digital/tapestry-wp/issues/94
=> !MERGE: Removed scrollTo and fixed onPageUpdate so the supplied method is called

src/server/render/default-html.js
Moved our `vendor`/`bundle` JS above any 3rd party JS declared through `react-helmet`
There was no way to load a script through `react-helmet` and have it load after the `vendor`/`bundle`
No tests broken
=> 1st-party scripts can now run before 3rd party scripts

src/server/index.js, src/shared/default-routes.js, src/shared/loader-categories.js, src/shared/loader-front-page.js, src/shared/loader-page.js, src/shared/loader-post.js, test/tests/component.test.js, test/tests/document.test.js, test/tests/proxies.test.js, test/utils.js
I've updated the default routes and loading schemas to match the WordPress defaults for Permalinks and the mock API to represent the WP-API as of version `4.7.3`A
Post: `/year/month/day/post-slug`
Category: `/category/my-category-name/sub-category`
Pages: `/page-slug/sub-page-slug`
// Todo
Tag: `/tag/post-tag-slug`
Author: `/author/author-slug`
Forces us to look at customisable routing, and also allows more WordPress sites to work out of the box. It also ties in with the quick-start section of the documentation 
All test passing.
=> Replace default routing with WordPress defaults

src/server/handle-dynamic.js, src/server/handle-redirects.js, src/server/index.js, src/utilities/validator.js, test/tests/redirects.test.js
Added server-side redirect paths for Tapestry. Validator for the config and tests.
Projects should be able to configure server-side only redirects.
New tests written, all tests passing. Testing is great. This _demonstrably works_ without unintended side-effects.
=> Initial work on redirect handler

src/webpack/client.config.js, src/webpack/server.config.js
Added a `new webpack.DefinePlugin({ __DEV__ })` to expose a `__DEV__` global variable for the user
[#87](https://github.com/shortlist-digital/tapestry-wp/issues/87)
=> Exposed __DEV__ through webpack.defineplugin

src/server/handle-dynamic.js
Pulled the error handler to be executed as soon as we get our callback called from `async-props` will allow us to pass the error back to the user's client.
If we don't immediately fail when receiving an error from `async-props`, we'll get an `Unhandled Promise rejection` warning (and an hanging server) when trying to access `asyncProps.propsArray[0]`, since `asyncProps` would most likely be `undefined`.
=> fix: fail first on error from async-props

src/server/render/index.js, src/shared/default-routes.js, src/utilities/logger.js, src/utilities/validator.js, test/tests/component.test.js
Renamed the `Error` component to `CustomError` to avoid using a reserved term, happy to hear suggestions for another name.
Added a simple test to see if the `CustomError` component is being called on un-matched route.
Fixes #112
=> Rename error component

src/utilities/validator.js
Removed `loaders` and `frontPage` from `tapestry.config.js`. `joi` can't return custom error messages without overriding all other error messages. e.g. `joi.string().error('This is a custom error')` will _only_ return this error regardless of other errors in the object.
Replaced `logErrorObject` with `errorMessage` as we're only returning a string from `joi`
Fixes #114 #113 #60
=> Deprecate config options

bootstrap/components/page.js, bootstrap/components/post.js, package.json, src/server/render/default-html.js, src/shared/fetch-data.js, src/shared/progress-indicator.js, src/webpack/server.config.js
Replaced React `PropTypes` with `prop-types` package as recommended by FB, temporarily silencing `webpack` `loader-utils` deprecation warning.
This was an attempt at removing all 5 deprecation warnings when booting tapestry, although I don't think we can do much about most of them.
* React warnings are coming from `async-props`, which I assume won't ever be fixed (a year since the last update)
* The `webpack` warning is a `babel-loader` issue, we're waiting on the `7.0.0` release to fix this
* `glamor` version 3 is still in beta so we can't remove these warnings until we upgrade
=> Handle deprecated dependency warnings

src/shared/fetch-data.js
The weird array like object syntax was appearing because we spread the array on the `TopLevelComponent`, React was converting it to an object.
Future talk, we should probably re-name this component and split out the data normalisation bit, perhaps the key `posts` should be dynamic based on the API endpoint, e.g. `tags`, `users`, `categories`.
Fixes #127
=> Simplified data normalisation

src/server/render/default-html.js, test/tests/document.test.js, test/tests/routing.test.js
I have changed the `JSON.stringify` call in `default-html.js` to include `.replace` calls to escape any HTML tags. This approach is taken from: https://github.com/mapbox/safer-stringify
This was causing any embedded `<script>` tags to be parsed by the browser as tags and not strings – meaning the `<script>` for the `window.__ASYNC_PROPS__` was closed by any `</script>` in the JSON string.
Updated tests
=> escape slashes to prevent </script> in JSON in __ASYNC_PROPS__

src/shared/fetch-data.js
I have fixed an issue where `<AsyncPropsWrapper />` was re-rendering it's children when it's data didn't change.
This has been achieved by adding a check in `shouldComponentUpdate()`, and removing the `forceUpdate()` call in `componentWillReceiveProps()`.
I have also moved the `scrollTop()` and `onPageUpdate()` calls inside `componentDidMount()` and `componentDidUpdate()`, to ensure we are at the top of the new page and the `onPageUpdate` is called on initial and subsequent view renders.
We were having unnecessary re-renders of the entire component tree on client-side navigation, before the next view had been rendered.
=> Update <AsyncPropsWrapper /> to only re-render when new data received

package.json, src/server/handle-api.js, src/server/handle-dynamic.js, src/server/handle-purge.js, src/server/index.js
Added the logging libary: https://github.com/winstonjs/winston
When you run tapestry or the tests, you can now define a `LOG_LEVEL` environment variable when you run the application, this is mapped to Winston's internal logging levels.
For example:
`LOG_LEVEL=debug npm test` will mean tapestry logs out all the statements with the log level... you guessed it: debug
`winston.log('debug', 'this is some stuff I only want to read if LOG_LEVEL=debug')`
More logging = more bug fixing. I found a purge bug straight away!
All the tests are passing!
=> Winston logging

src/webpack/shared.js
Enabled webpack's directory cache
Saw this tweet: https://twitter.com/TheLarkInn/status/879315255851077632
Cuts 3.5 to 4 seconds off Webpack compile times on my personal machine.
=> Enable webpack directory cache

src/server/handle-api.js, src/server/handle-dynamic.js, src/utilities/cache-manager.js, test/tests/cache.test.js
Added a terrible piece of regex to normalise the cache keys. Applied to `siteUrl` in API handler as it was sometimes doubling up the first `/`.
Also added and updated a bunch of the debug logs to improve their usefulness.
#206 
Added tests for setting cache items and retrieving them
=> Added normalisation method for cache keys, updated and added debug logs

src/server/index.js
Switched on default security preference in Hapi, these options cover off a couple of issues including #218 #217 #216 
I noticed that it doesn't contain a Content Security Policy so I'm going to look at including it manually. _Unless_ we want to modify the headers through the `tapestry.config.js`?
https://hapijs.com/api#route-options
=> !MERGE - Improve server security

src/utilities/logger.js
`winston` errors out if it can't find the directory to store the log file, in this case `.tapestry/`. We should fix this and keep the log file, but for now to get `2.0.0-14` ready for production we need to remove it.
=> Temporarily removing the tapestry.log file as it was erroring on a fresh build

src/server/handle-static.js
As far as I can tell Hapi doesn't support a cache expiry date, only a relative `expiresIn` value in milliseconds. https://hapijs.com/api#route-options
Fixes #223
=> Added a year long cache for static script files

package.json, src/server/index.js, src/utilities/validator.js, yarn.lock
Shifted registering the plugins until after `connection` as per Hapis [docs](https://hapijs.com/api#serverregisterplugins-options-callback), also logging any plugin errors at registration time.
Tested locally and it redirects to `https`, `https://0.0.0.0:3030` doesn't work but I'm assuming we'll have no issue.
Fixes #210
=> Added hapi-require-https to Hapi plugins

src/shared/handle-api-response.js, test/tests/response.test.js
Test and fix for statically registered routes being return with 404 status codes. Try any Tapestry project on the latest version that has statically registered routes. You'll see in dev tools that the `document` is being returned with a 404 status.
404 response codes are bad when we are responding correctly.
Includes a test.
=> Fix for 404 bug

src/server/handle-redirects.js, test/tests/redirects.test.js
Allow underlying Hapi server to rewrite HTTP verbs during redirect requests:
`308` will become `301`
IE10/IE11 do not support 308 redirects
Updated the test in `redirects.test.js`
=> Use 301 status for redirects for IE 10/11 compatibility

src/server/handle-dynamic.js, test/tests/response.test.js
Fix https://github.com/shortlist-digital/tapestry-wp/issues/249
Don't want to cache previews on the CDN
New tests written
=> Handle preview endpoints and don't set a cache header

src/server/handle-dynamic.js, test/tests/cache.test.js
HTML cache no ignores query parameters
Lots of URLs include Dotmailer or Google tracking with unique IDs. They're entering the cache as unique entrants which was essentially rendering the HTML cache redundant.
New test aded. All tests passed.
=> Add test and fix caching bug, where query params were cached

src/server/handle-api.js, src/utilities/validator.js, test/tests/wordpress-dot-com.test.js
I've added  new configuration to the `tapestry.config.js` that allows you to use wordpress.com's free blog hosting to power Tapestry:
API endpoints are configured as such:
`https://public-api.wordpress.com/wp/v2/sites/en.blog.wordpress.com/`
Configuration looks like this:
```
{
components: {
Post: Post
},
siteUrl: 'http://dummy.site.wordpress.com',
options: {
wordpressDotComHosting: true
}
}
```
Really cool to support and it means you don't even need to pay to host a WordPress site, you can just get going with Tapestry straight away.
New tests written to check the data loading from those endpoints
=> Wordpress.com API Integration

test/tests/redirects.test.js
Added a test for odd characters in a redirects file
Not unfeasible that some may need odd characters in legacy redirects and I wanted to make sure they worked
It's a test.
=> Add test for strange redirects

.eslintrc.json, circle.yml, package.json, src/server/handle-api.js, src/server/handle-dynamic.js, src/utilities/cache-manager.js, test/tests/cache.test.js, yarn.lock
I've used `async/await` in Node 7.6 (6 months old), to implement this quickly without refactoring much. Is this a breaking change to version 3? Potentially.... @thomasdigby Whaddya think, probably not many people using it beyond us, and I've update the package.json, so I think it would throw if you weren't using at least 7 to run it, technically it's not an API change. Not sure what semver says about this.
I found the pluggable cache manager framework - rewritten the current caching implementation. It uses the new framework - and I'm hoping to add configuration via a cache.config.js (so nothing gets bundled in the frontend), which would allow a project to use any of the [flexible caching options availaibe in `node-cache-manager`](https://github.com/BryanDonovan/node-cache-manager#store-eng …
=> !MERGE - Feature/cache manager

src/server/index.js
Removed the X-Frame-Options header in the default security options.
This option is too strict by default, it's required for us to render a site in FB IA. 
Tested the headers in browser
=> Removed X-Frame-Options

src/server/handle-redirects.js
I've moved the redirect handler from firing _after_ everything else has shaken out and a 404 is detected, to checking before each request.
v8 can read from an object with a key at a rate of ~100,000,000 operations per second, so this doesn't really affect performance.
Redirects are failing some instances, probably because of incorrectly cached status codes - but there's actually no point detangling it. Keep it simple etc.
All the tests work.
=> Move redirects handler to front of request queue to 'get them over with'
