shortlist-digital/tapestry-wp

src/boot.js, src/default-html.js, src/server.js, src/webpack.config.js
Updated bundle output location, updated compiledTree location to .tapestry dir
=> Updated output directories

bin/tapestry-build, src/build.js, src/server.js
=> Improve console logs errors

circle.yml, package.json
Added the relevant files needed to stop these freaking CircleCI builds failing _all the time_
=> Fix build errors

bin/tapestry-build, bin/tapestry-dev, bin/tapestry-start, package.json, src/build.js, src/logger.js, src/server.js
Added a logger to handle CLI messaging throughout Tapestry.
To make the messaging consistent, providing a base to work on proper error handling and how it's communicated.
Fixes #30
=> Improve cli logging

bin/tapestry-dev, package.json
Added validation check to `siteUrl`
Extra validation and feedback to the user is always useful
Fixes #63
=> Validating siteUrl on tapestry dev

src/server/handle-api.js
Removed erroneous fetch code that modified the API response
Breaks everything
Tested locally with SS17 and all the test continue to pass
=> remove code that modifies data response

src/server/index.js
`X-Powered-By: Tapestry` header
=> very important codez

README.md, package.json, src/shared/loader-categories.js, src/shared/loader-front-page.js, src/shared/loader-page.js, src/shared/loader-post.js, test/tests/component.test.js, test/tests/document.test.js, test/utils.js
Reverted routing updates to allow us to publish this patch, I'll reapply the routing updates to the v2 branch.
=> Publish 1.7.4

package.json, src/client/webpack.entry.js, src/server/handle-dynamic.js, src/server/render/default-html.js, src/shared/fetch-data.js, src/shared/route-wrapper.js
Moved some of your naming changes and fixes to a separate PR
I'm waiting for a MigrateDB
Tests all pass
=> Minor naming updates and hotfixes

README.md, package.json, test/components/page.js, test/tests/component.test.js, test/utils.js
Merging missing updates from `develop`
=> Merged develop

src/client/index.js, src/server/handle-dynamic.js, src/server/index.js, src/utilities/logger.js, src/utilities/validator.js
Just checking in with you @jonsherrard, this closely matches your commit, is it good to publish?
=> logging errorObject to console

src/shared/progress-indicator.js
Moved dynamic CSS properties to inline styles
Updating the properties in a Glamor `css` method was creating a new classname and appending styles to the Browser StyleSheet every state update. Rendering felt slow.
Tested in browser
=> Inline progress update

src/shared/progress-indicator.js
Tweaked timings/percentage increase, switched default colour to Shortlist Studio turquoise, removed glamor dependency.
=> Minor progress indicator updates

src/server/handle-api.js, src/server/handle-dynamic.js, src/server/handle-preview.js, src/server/index.js, src/shared/fetch-route-data.js, test/tests/routing.test.js
Integrated custom draft API to match [WP Tapestry Plugin](https://github.com/shortlist-digital/wp-tapestry-plugin). Still need to write tests.
=> Wordpress preview integration

src/index.js, src/utilities/create-compilers.js
=> Logging a notice to the CLI when using a custom babelrc

bin/tapestry-development, bin/tapestry-start, src/webpack/client.config.js, src/webpack/server.config.js
Also, removed the weird suffix on server bundles.
=> Remove stats.json from production build

test/tests/proxies.test.js
Wrote a test to see if you can pass in `{params}` to proxy paths
=> Wrote a test for some proxy paths with wildcards

src/server/index.js
=> Added isCaseSensitive option to Server config

test/tests/redirects.test.js
Added a test for reading the `redirects.json` file from the Tapestry project directory
For some reason couldn't figure out how to do it when I wrote the functionality.
It's a test!
=> Added a test for the redirects.json file functionality

package.json, src/webpack/client.config.js, yarn.lock
Added an es6 `Symbol` bundle to the webpack config
Fixes this React bug: https://github.com/facebook/react/issues/8379
Internal test and tested in ie10/11 on Browserstack
=> Add polyfill of es6 symbol to client bundle

CHANGELOG.md, src/server/handle-redirects.js, test/tests/redirects.test.js
Cutting a release with cacheBust for redirects.json
_Need it for some projects_
=> Release v2.2.0

src/server/handle-redirects.js, test/tests/redirects.test.js
Made redirects case insensitive
The rest of the routing works that way
Added a new test
=> Case insensitive redirects

README.md
=> !MERGE - OSS-ify
